lxc exec $1 -- wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | sudo apt-key add -
lxc exec $1 -- sh -c "echo 'deb https://download.jitsi.org stable/' > /etc/apt/sources.list.d/jitsi-stable.list"
sleep 1
lxc exec $1 -- apt-get -y update
lxc exec $1 -- apt-get -y install jitsi-meet
lxc exec $1 -- echo "org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=$CONTAINER_IP" >> /etc/jitsi/videobridge/sip-communicator.properties
lxc exec $1 -- echo "org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=$PUBLIC_IP" >> /etc/jitsi/videobridge/sip-communicator.properties
