#!/bin/bash

update () {
  git pull #https://github.com/aaronstuder/lxq.git /opt/lxq/
  exit 0;
}

init () {
  update
  /opt/lxq/init
}

nextcloud () {
  update
  /opt/lxq/apps/nextcloud/nextcloud-install
}

rocketchat () {
  update
  /opt/lxq/apps/nextcloud/rocketchat-install
}

install () {
  update
  /opt/lxq/apps/$2/$2-install
}

$1
