#!/bin/bash

update () {
  git pull https://github.com/aaronstuder/lxq.git /opt/lxq/
  exit 0;
}

init () {
  update()
  /opt/lxq/init
}

nextcloud () {
  update()
  /opt/lxq/scripts/nextcloud-install
}

rocketchat () {
  update()
  /opt/lxq/scripts/rocketchat-install
}

$1
