#!/bin/bash

source /etc/lxq/lxq.cfg

if [ -z "$LXQ_LE_EMAIL" ]
then
echo
echo "What is your email address? [Used for Let’s Encrypt]"
read LXQ_LE_EMAIL
sed -i "s/LXQ_LE_EMAIL=/LXQ_LE_EMAIL=$LXQ_LE_EMAIL/g" /etc/lxq/lxq.cfg
fi
if [ -z "$LXQ_WILDCARD" ]
then
echo
echo "What is your domain name?"
read LXQ_WILDCARD
sed -i "s/LXQ_WILDCARD=/LXQ_WILDCARD=$LXQ_WILDCARD/g" /etc/lxq/lxq.cfg
fi
A=*.
WC_DOMAIN="$A$LXQ_WILDCARD
echo "Installing Wildcard Certificate for $domain_name..."
#lxc exec nginx -- certbot certonly --dns-cloudflare --dns-cloudflare-credentials /root/.secrets/certbot/cloudflare.ini -d $LXQ_WILDCARD  -d $WC_DOMAIN --agree-tos --noninteractive --manual-public-ip-logging-ok --email $LXQ_LE_EMAIL
