#!/bin/bash
echo
echo "What is your email address? [Used for Let’s Encrypt]"
read email
echo
echo "What is your domain name?"
read domain_name
echo
a='*.'
c="$a$domain_name"
echo "Installing Wildcard Certificate for $domain_name..."
lxc file push cloudflare.ini nginx/root/
lxc exec $n -- certbot certonly --dns-cloudflare --dns-cloudflare-credentials /root/.secrets/cloudflare.ini -d $domain_name  -d c$ --agree-tos --noninteractive --manual-public-ip-logging-ok --email $email
