#!/bin/bash
#this entire script could probably be a function?
CONTAINER=openvpn # variable names should always be obvious and self-explanitory

echo "Creating Container:" $CONTAINER
lxc launch images:ubuntu/18.04 $CONTAINER # get fresh image directly from lxd servers
#echo "Getting IP Address"
#sleep 5s #no
CONTAINER_LOCAL_IP=$(lxc list $CONTAINER -c 4 --format csv | awk '{print $1}') # much simpler method of displaying IP. If a container has more than one IP (a container is using a vpn for example), the awk statement could cause issues. In the future this should validate the IP to make sure nothing funky happened.

echo "IP Address:" $IP
echo "Updating Container..."
#sleep 5s #no
lxc exec $CONTAINER -- apt update && lxc exec $CONTAINER -- apt dist-upgrade -y
echo "Update complete"
echo "Installing OpenVPN..."
lxc exec $CONTAINER -- wget https://raw.githubusercontent.com/Angristan/openvpn-install/master/openvpn-install.sh
lxc exec $CONTAINER -- chmod +x openvpn-install.sh
lxc exec $CONTAINER -- sh -c "./openvpn-install.sh"
echo
HOST_PUBLIC_IP=$(curl -4 ifconfig.co)
echo "Public IP:" $HOST_PUBLIC_IP
echo "Updating iptables to forward $HOST_PUBLIC_IP:1194/udp to $CONTAINER Container"
echo
iptables -t nat -I PREROUTING -i eth0 -p UDP -d $HOST_PUBLIC_IP --dport 1194 -j DNAT --to-destination $CONTAINER_LOCAL_IP:1194
netfilter-persistent save
echo "Here are your current PREROUTING Rules:"
echo
iptables -t nat -L PREROUTING
echo "Setup Complete!"
echo
