#!/bin/bash
CONTAINER=nextcloud
echo "Enter Domain Name:"
read DOMAIN_NAME
echo
echo "Creating Container $CONTAINER..."
lxc launch images:ubuntu/18.04 $CONTAINER
echo
echo "Getting IP Address..."
CONTAINER_LOCAL_IP=$(lxc list -c 4 --format csv | awk '{print $1}')
echo
echo "IP Address is $CONTAINER_LOCAL_IP"
echo
echo "Updating Container..."
sleep 3s
lxc exec $CONTAINER -- apt-get update
lxc exec $CONTAINER -- apt-get upgrade -y
echo

echo "Installing $C"
lxc exec nextcloud -- snap install nextcloud
echo

echo "Pulling .conf file..."
# If we're using git clone, the file should already be on the system.
cd $LXQ_PATH/apps/nextcloud
#wget -nc https://raw.githubusercontent.com/aaronstuder/lxq/master/apps/nextcloud/nextcloud.conf
sed -i "s/<<domain_name>>/$domain_name/g" nextcloud.conf
sed -i "s/<<IP>>/$CONTAINER_LOCAL_IP/g" nextcloud.conf
echo
echo "Pushing .conf file to container..."
lxc file push nextcloud.conf nginx/etc/nginx/conf.d/

echo "Restarting nginx..."
lxc restart nginx
echo
echo "Generating Certificates..."
# DO NOT HARDCODE THIS WITH YOUR EMAIL. This may be something that needs to be left up to the user.
#lxc exec nginx -- certbot --nginx -n --email aaronstuder@gmail.com --agree-tos --domains $domain_name --redirect
echo Done!

