# Download the script
lxc exec $1 -- wget https://raw.githubusercontent.com/BookStackApp/devops/master/scripts/installation-ubuntu-18.04.sh

# Make it executable
lxc exec $1 -- chmod a+x installation-ubuntu-18.04.sh

# Run the script with admin permissions
lxc exec $1 -- sudo ./installation-ubuntu-18.04.sh $1.$DOMAIN_NAME

# Updates .env file with correct domain
lxc exec $1 --  sed -i "s,#APP_URL=https://example.com,APP_URL=https://$1.$DOMAIN_NAME,g" /var/www/bookstack/.env
