lxc exec $1 -- curl -sSL https://get.docker.com/ | CHANNEL=stable sh
# After the installation process is finished, you may need to enable the service and make sure it is started (e.g. CentOS 7)
lxc exec $1 -- systemctl enable docker.service
lxc exec $1 -- systemctl start docker.service
lxc exec $1 -- curl -L https://github.com/docker/compose/releases/download/$(curl -Ls https://www.servercow.de/docker-compose/latest.php)/docker-compose-$(uname -s)-$(uname -m) > /usr/local/bin/docker-compose
lxc exec $1 -- chmod +x /usr/local/bin/docker-compose
lxc exec $1 -- cd /opt
lxc exec $1 -- git clone https://github.com/mailcow/mailcow-dockerized
lxc exec $1 -- cd mailcow-dockerized
