lxc exec $1 -- apt-get install apt-transport-https -y

# Add the release PGP keys:
lxc exec $1 -- curl -s https://syncthing.net/release-key.txt | sudo apt-key add -

# Add the "stable" channel to your APT sources:
lxc exec $1 -- echo "deb https://apt.syncthing.net/ syncthing stable" | sudo tee /etc/apt/sources.list.d/syncthing.list

# Update and install syncthing:
lxc exec $1 -- apt-get update
lxc exec $1 -- apt-get install syncthing -y
